#!/usr/bin/env python3
# coding: utf-8

# Copyright (C) 2017-present Robert Griesel
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>

import gi
gi.require_version('Gtk', '4.0')
from gi.repository import Gtk, GLib

import os.path

from lemma.infrastructure.service_locator import ServiceLocator
from lemma.ui.popovers.popover_manager import PopoverManager
from lemma.db.character_db import CharacterDB


class ToolsSidebar(Gtk.ScrolledWindow):

    def __init__(self):
        Gtk.ScrolledWindow.__init__(self)
        self.set_size_request(262, 280)

        self.resources_path = ServiceLocator.get_resources_path()

        self.box = Gtk.Box.new(Gtk.Orientation.VERTICAL, 0)
        self.box.add_css_class('tools-sidebar')

        self.add_headline('Math Typesetting', 'first')

        symbols = []
        symbols.append(['sqrt', 'win.insert-xml(\'<mathroot><mathlist><placeholder marks="new_selection_bound prev_selection"/><end marks="new_insert"/></mathlist><mathlist></mathlist></mathroot>\')'])
        symbols.append(['nthroot', 'win.insert-xml(\'<mathroot><mathlist><placeholder marks="new_selection_bound prev_selection"/><end marks="new_insert"/></mathlist><mathlist><placeholder/><end/></mathlist></mathroot>\')'])
        symbols.append(['subscript', 'win.insert-xml(\'<placeholder marks="prev_selection"/><mathscript><mathlist><placeholder marks="new_selection_bound"/><end marks="new_insert"/></mathlist><mathlist></mathlist></mathscript>\')'])
        symbols.append(['superscript', 'win.insert-xml(\'<placeholder marks="prev_selection"/><mathscript><mathlist></mathlist><mathlist><placeholder marks="new_selection_bound"/><end marks="new_insert"/></mathlist></mathscript>\')'])
        symbols.append(['subsuperscript', 'win.insert-xml(\'<placeholder marks="prev_selection"/><mathscript><mathlist><placeholder marks="new_selection_bound"/><end marks="new_insert"/></mathlist><mathlist><placeholder/><end/></mathlist></mathscript>\')'])
        self.add_flowbox(symbols)

        symbols = []
        symbols.append(['sumwithindex', 'win.insert-xml(\'∑<mathscript><mathlist><placeholder/>=<placeholder/><end/></mathlist><mathlist><placeholder/><end/></mathlist></mathscript> <placeholder marks="prev_selection"/>\')'])
        symbols.append(['prodwithindex', 'win.insert-xml(\'∏<mathscript><mathlist><placeholder/>=<placeholder/><end/></mathlist><mathlist><placeholder/><end/></mathlist></mathscript> <placeholder marks="prev_selection"/>\')'])
        symbols.append(['indefint', 'win.insert-xml(\'∫ <placeholder marks="prev_selection"/> 𝑑<placeholder/>\')'])
        symbols.append(['defint', 'win.insert-xml(\'∫<mathscript><mathlist><placeholder/><end/></mathlist><mathlist><placeholder/><end/></mathlist></mathscript> <placeholder marks="prev_selection"/> 𝑑<placeholder/>\')'])
        self.add_flowbox_for_pictures(symbols)

        self.add_headline('Punctuation')

        symbols = []
        symbols.append(['textendash', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('textendash')])
        symbols.append(['textemdash', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('textemdash')])
        symbols.append(['guillemetleft', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('guillemetleft')])
        symbols.append(['guillemetright', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('guillemetright')])
        symbols.append(['quotedblbase', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('quotedblbase')])
        symbols.append(['textquotedblleft', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('textquotedblleft')])
        symbols.append(['textquotedblright', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('textquotedblright')])
        symbols.append(['cdotp', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('cdotp')])
        symbols.append(['colon', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('colon')])
        symbols.append(['vdots', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('vdots')])
        symbols.append(['cdots', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('cdots')])
        self.add_flowbox(symbols)

        self.symbols = list()

        self.greek_sym = []
        self.greek_sym.append(['alpha', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('alpha')])
        self.greek_sym.append(['beta', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('beta')])
        self.greek_sym.append(['gamma', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('gamma')])
        self.greek_sym.append(['delta', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('delta')])
        self.greek_sym.append(['epsilon', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('epsilon')])
        self.greek_sym.append(['zeta', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('zeta')])
        self.greek_sym.append(['eta', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('eta')])
        self.greek_sym.append(['theta', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('theta')])
        self.greek_sym.append(['vartheta', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('vartheta')])
        self.greek_sym.append(['iota', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('iota')])
        self.greek_sym.append(['kappa', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('kappa')])
        self.greek_sym.append(['lambda', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('lambda')])
        self.greek_sym.append(['mu', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mu')])
        self.greek_sym.append(['nu', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('nu')])
        self.greek_sym.append(['xi', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('xi')])
        self.greek_sym.append(['pi', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('pi')])
        self.greek_sym.append(['varpi', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('varpi')])
        self.greek_sym.append(['rho', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('rho')])
        self.greek_sym.append(['varrho', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('varrho')])
        self.greek_sym.append(['sigma', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('sigma')])
        self.greek_sym.append(['varsigma', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('varsigma')])
        self.greek_sym.append(['tau', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('tau')])
        self.greek_sym.append(['upsilon', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('upsilon')])
        self.greek_sym.append(['phi', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('phi')])
        self.greek_sym.append(['varphi', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('varphi')])
        self.greek_sym.append(['chi', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('chi')])
        self.greek_sym.append(['psi', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('psi')])
        self.greek_sym.append(['omega', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('omega')])
        self.greek_sym.append(['Gamma', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('Gamma')])
        self.greek_sym.append(['Delta', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('Delta')])
        self.greek_sym.append(['Theta', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('Theta')])
        self.greek_sym.append(['Lambda', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('Lambda')])
        self.greek_sym.append(['Xi', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('Xi')])
        self.greek_sym.append(['Pi', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('Pi')])
        self.greek_sym.append(['Sigma', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('Sigma')])
        self.greek_sym.append(['Upsilon', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('Upsilon')])
        self.greek_sym.append(['Phi', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('Phi')])
        self.greek_sym.append(['Psi', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('Psi')])
        self.greek_sym.append(['Omega', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('Omega')])
        self.symbols.append({'id': 'greek', 'name': 'Greek Letters', 'symbols': self.greek_sym})

        self.misc_sym = []
        self.misc_sym.append(['neg', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('neg')])
        self.misc_sym.append(['infty', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('infty')])
        self.misc_sym.append(['prime', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('prime')])
        self.misc_sym.append(['backslash', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('backslash')])
        self.misc_sym.append(['emptyset', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('emptyset')])
        self.misc_sym.append(['forall', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('forall')])
        self.misc_sym.append(['exists', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('exists')])
        self.misc_sym.append(['nexists', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('nexists')])
        self.misc_sym.append(['complement', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('complement')])
        self.misc_sym.append(['bot', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('bot')])
        self.misc_sym.append(['top', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('top')])
        self.misc_sym.append(['partial', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('partial')])
        self.misc_sym.append(['nabla', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('nabla')])
        self.misc_sym.append(['mathbbN', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mathbbN')])
        self.misc_sym.append(['mathbbZ', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mathbbZ')])
        self.misc_sym.append(['mathbbQ', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mathbbQ')])
        self.misc_sym.append(['mathbbI', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mathbbI')])
        self.misc_sym.append(['mathbbR', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mathbbR')])
        self.misc_sym.append(['mathbbC', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mathbbC')])
        self.misc_sym.append(['Im', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('Im')])
        self.misc_sym.append(['Re', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('Re')])
        self.misc_sym.append(['aleph', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('aleph')])
        self.misc_sym.append(['wp', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('wp')])
        self.misc_sym.append(['hbar', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('hbar')])
        self.misc_sym.append(['imath', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('imath')])
        self.misc_sym.append(['jmath', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('jmath')])
        self.misc_sym.append(['ell', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('ell')])
        self.misc_sym.append(['sharp', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('sharp')])
        self.misc_sym.append(['flat', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('flat')])
        self.misc_sym.append(['natural', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('natural')])
        self.misc_sym.append(['angle', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('angle')])
        self.misc_sym.append(['sphericalangle', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('sphericalangle')])
        self.misc_sym.append(['measuredangle', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('measuredangle')])
        self.misc_sym.append(['clubsuit', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('clubsuit')])
        self.misc_sym.append(['diamondsuit', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('diamondsuit')])
        self.misc_sym.append(['heartsuit', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('heartsuit')])
        self.misc_sym.append(['spadesuit', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('spadesuit')])
        self.misc_sym.append(['eth', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('eth')])
        self.misc_sym.append(['mho', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mho')])
        self.symbols.append({'id': 'misc', 'name': 'Misc. Symbols', 'symbols': self.misc_sym})

        self.operators_sym = []
        self.operators_sym.append(['pm', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('pm')])
        self.operators_sym.append(['mp', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mp')])
        self.operators_sym.append(['setminus', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('setminus')])
        self.operators_sym.append(['cdot', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('cdot')])
        self.operators_sym.append(['times', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('times')])
        self.operators_sym.append(['ast', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('ast')])
        self.operators_sym.append(['star', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('star')])
        self.operators_sym.append(['divideontimes', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('divideontimes')])
        self.operators_sym.append(['circ', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('circ')])
        self.operators_sym.append(['bullet', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('bullet')])
        self.operators_sym.append(['div', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('div')])
        self.operators_sym.append(['cap', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('cap')])
        self.operators_sym.append(['cup', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('cup')])
        self.operators_sym.append(['uplus', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('uplus')])
        self.operators_sym.append(['sqcap', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('sqcap')])
        self.operators_sym.append(['sqcup', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('sqcup')])
        self.operators_sym.append(['triangleleft', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('triangleleft')])
        self.operators_sym.append(['triangleright', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('triangleright')])
        self.operators_sym.append(['wr', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('wr')])
        self.operators_sym.append(['bigtriangleup', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('bigtriangleup')])
        self.operators_sym.append(['bigtriangledown', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('bigtriangledown')])
        self.operators_sym.append(['vee', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('vee')])
        self.operators_sym.append(['wedge', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('wedge')])
        self.operators_sym.append(['oplus', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('oplus')])
        self.operators_sym.append(['ominus', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('ominus')])
        self.operators_sym.append(['otimes', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('otimes')])
        self.operators_sym.append(['oslash', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('oslash')])
        self.operators_sym.append(['odot', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('odot')])
        self.operators_sym.append(['circledcirc', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('circledcirc')])
        self.operators_sym.append(['circleddash', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('circleddash')])
        self.operators_sym.append(['circledast', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('circledast')])
        self.operators_sym.append(['dotplus', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('dotplus')])
        self.operators_sym.append(['leftthreetimes', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('leftthreetimes')])
        self.operators_sym.append(['rightthreetimes', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('rightthreetimes')])
        self.operators_sym.append(['ltimes', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('ltimes')])
        self.operators_sym.append(['rtimes', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('rtimes')])
        self.operators_sym.append(['dagger', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('dagger')])
        self.operators_sym.append(['ddagger', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('ddagger')])
        self.operators_sym.append(['intercal', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('intercal')])
        self.operators_sym.append(['amalg', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('amalg')])
        self.symbols.append({'id': 'operators', 'name': 'Operators', 'symbols': self.operators_sym})

        self.relations_sym = []
        self.relations_sym.append(['leq', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('leq')])
        self.relations_sym.append(['geq', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('geq')])
        self.relations_sym.append(['lneq', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('lneq')])
        self.relations_sym.append(['gneq', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('gneq')])
        self.relations_sym.append(['nleq', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('nleq')])
        self.relations_sym.append(['ngeq', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('ngeq')])
        self.relations_sym.append(['nless', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('nless')])
        self.relations_sym.append(['ngtr', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('ngtr')])
        self.relations_sym.append(['ll', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('ll')])
        self.relations_sym.append(['gg', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('gg')])
        self.relations_sym.append(['neq', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('neq')])
        self.relations_sym.append(['equiv', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('equiv')])
        self.relations_sym.append(['approx', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('approx')])
        self.relations_sym.append(['sim', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('sim')])
        self.relations_sym.append(['simeq', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('simeq')])
        self.relations_sym.append(['cong', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('cong')])
        self.relations_sym.append(['ncong', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('ncong')])
        self.relations_sym.append(['asymp', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('asymp')])
        self.relations_sym.append(['prec', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('prec')])
        self.relations_sym.append(['succ', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('succ')])
        self.relations_sym.append(['nprec', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('nprec')])
        self.relations_sym.append(['nsucc', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('nsucc')])
        self.relations_sym.append(['preceq', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('preceq')])
        self.relations_sym.append(['succeq', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('succeq')])
        self.relations_sym.append(['subset', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('subset')])
        self.relations_sym.append(['supset', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('supset')])
        self.relations_sym.append(['subseteq', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('subseteq')])
        self.relations_sym.append(['supseteq', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('supseteq')])
        self.relations_sym.append(['subsetneq', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('subsetneq')])
        self.relations_sym.append(['supsetneq', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('supsetneq')])
        self.relations_sym.append(['nsubseteq', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('nsubseteq')])
        self.relations_sym.append(['nsupseteq', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('nsupseteq')])
        self.relations_sym.append(['sqsubset', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('sqsubset')])
        self.relations_sym.append(['sqsupset', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('sqsupset')])
        self.relations_sym.append(['sqsubseteq', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('sqsubseteq')])
        self.relations_sym.append(['sqsupseteq', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('sqsupseteq')])
        self.relations_sym.append(['bowtie', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('bowtie')])
        self.relations_sym.append(['in', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('in')])
        self.relations_sym.append(['notin', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('notin')])
        self.relations_sym.append(['propto', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('propto')])
        self.relations_sym.append(['vdash', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('vdash')])
        self.relations_sym.append(['dashv', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('dashv')])
        self.relations_sym.append(['models', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('models')])
        self.relations_sym.append(['smile', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('smile')])
        self.relations_sym.append(['frown', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('frown')])
        self.relations_sym.append(['between', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('between')])
        self.relations_sym.append(['perp', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('perp')])
        self.relations_sym.append(['mid', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mid')])
        self.relations_sym.append(['nmid', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('nmid')])
        self.relations_sym.append(['parallel', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('parallel')])
        self.relations_sym.append(['nparallel', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('nparallel')])
        self.relations_sym.append(['vartriangleleft', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('vartriangleleft')])
        self.relations_sym.append(['vartriangleright', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('vartriangleright')])
        self.relations_sym.append(['ntriangleleft', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('ntriangleleft')])
        self.relations_sym.append(['ntriangleright', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('ntriangleright')])
        self.relations_sym.append(['trianglelefteq', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('trianglelefteq')])
        self.relations_sym.append(['trianglerighteq', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('trianglerighteq')])
        self.relations_sym.append(['ntrianglelefteq', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('ntrianglelefteq')])
        self.relations_sym.append(['ntrianglerighteq', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('ntrianglerighteq')])
        self.relations_sym.append(['multimap', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('multimap')])
        self.relations_sym.append(['pitchfork', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('pitchfork')])
        self.relations_sym.append(['therefore', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('therefore')])
        self.relations_sym.append(['because', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('because')])
        self.symbols.append({'id': 'relations', 'name': 'Relations', 'symbols': self.relations_sym})

        self.arrows_sym = []
        self.arrows_sym.append(['leftarrow', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('leftarrow')])
        self.arrows_sym.append(['leftrightarrow', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('leftrightarrow')])
        self.arrows_sym.append(['rightarrow', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('rightarrow')])
        self.arrows_sym.append(['longleftarrow', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('longleftarrow')])
        self.arrows_sym.append(['longleftrightarrow', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('longleftrightarrow')])
        self.arrows_sym.append(['longrightarrow', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('longrightarrow')])
        self.arrows_sym.append(['downarrow', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('downarrow')])
        self.arrows_sym.append(['updownarrow', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('updownarrow')])
        self.arrows_sym.append(['uparrow', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('uparrow')])
        self.arrows_sym.append(['Leftarrow', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('Leftarrow')])
        self.arrows_sym.append(['Leftrightarrow', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('Leftrightarrow')])
        self.arrows_sym.append(['Rightarrow', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('Rightarrow')])
        self.arrows_sym.append(['Longleftarrow', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('Longleftarrow')])
        self.arrows_sym.append(['Longleftrightarrow', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('Longleftrightarrow')])
        self.arrows_sym.append(['Longrightarrow', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('Longrightarrow')])
        self.arrows_sym.append(['Updownarrow', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('Updownarrow')])
        self.arrows_sym.append(['Uparrow', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('Uparrow')])
        self.arrows_sym.append(['Downarrow', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('Downarrow')])
        self.arrows_sym.append(['mapsto', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mapsto')])
        self.arrows_sym.append(['longmapsto', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('longmapsto')])
        self.arrows_sym.append(['leftharpoondown', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('leftharpoondown')])
        self.arrows_sym.append(['rightharpoondown', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('rightharpoondown')])
        self.arrows_sym.append(['leftharpoonup', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('leftharpoonup')])
        self.arrows_sym.append(['rightharpoonup', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('rightharpoonup')])
        self.arrows_sym.append(['rightleftharpoons', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('rightleftharpoons')])
        self.arrows_sym.append(['leftrightharpoons', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('leftrightharpoons')])
        self.arrows_sym.append(['downharpoonleft', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('downharpoonleft')])
        self.arrows_sym.append(['upharpoonleft', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('upharpoonleft')])
        self.arrows_sym.append(['downharpoonright', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('downharpoonright')])
        self.arrows_sym.append(['upharpoonright', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('upharpoonright')])
        self.arrows_sym.append(['nwarrow', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('nwarrow')])
        self.arrows_sym.append(['searrow', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('searrow')])
        self.arrows_sym.append(['nearrow', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('nearrow')])
        self.arrows_sym.append(['swarrow', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('swarrow')])
        self.arrows_sym.append(['hookleftarrow', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('hookleftarrow')])
        self.arrows_sym.append(['hookrightarrow', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('hookrightarrow')])
        self.arrows_sym.append(['curvearrowleft', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('curvearrowleft')])
        self.arrows_sym.append(['curvearrowright', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('curvearrowright')])
        self.arrows_sym.append(['Lsh', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('Lsh')])
        self.arrows_sym.append(['Rsh', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('Rsh')])
        self.arrows_sym.append(['looparrowleft', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('looparrowleft')])
        self.arrows_sym.append(['looparrowright', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('looparrowright')])
        self.arrows_sym.append(['leftrightsquigarrow', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('leftrightsquigarrow')])
        self.arrows_sym.append(['rightsquigarrow', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('rightsquigarrow')])
        self.symbols.append({'id': 'arrows', 'name': 'Arrows', 'symbols': self.arrows_sym})

        self.delimiters_sym = []
        self.delimiters_sym.append(['lparen', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('lparen')])
        self.delimiters_sym.append(['rparen', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('rparen')])
        self.delimiters_sym.append(['lbrack', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('lbrack')])
        self.delimiters_sym.append(['rbrack', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('rbrack')])
        self.delimiters_sym.append(['lbrace', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('lbrace')])
        self.delimiters_sym.append(['rbrace', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('rbrace')])
        self.delimiters_sym.append(['lfloor', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('lfloor')])
        self.delimiters_sym.append(['rfloor', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('rfloor')])
        self.delimiters_sym.append(['lceil', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('lceil')])
        self.delimiters_sym.append(['rceil', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('rceil')])
        self.delimiters_sym.append(['langle', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('langle')])
        self.delimiters_sym.append(['rangle', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('rangle')])
        self.delimiters_sym.append(['vert', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('vert')])
        self.delimiters_sym.append(['Vert', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('Vert')])
        self.symbols.append({'id': 'delimiters', 'name': 'Delimiters', 'symbols': self.delimiters_sym})

        self.mathcal_sym = []
        self.mathcal_sym.append(['mathcalA', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mathcalA')])
        self.mathcal_sym.append(['mathcalB', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mathcalB')])
        self.mathcal_sym.append(['mathcalC', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mathcalC')])
        self.mathcal_sym.append(['mathcalD', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mathcalD')])
        self.mathcal_sym.append(['mathcalE', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mathcalE')])
        self.mathcal_sym.append(['mathcalF', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mathcalF')])
        self.mathcal_sym.append(['mathcalG', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mathcalG')])
        self.mathcal_sym.append(['mathcalH', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mathcalH')])
        self.mathcal_sym.append(['mathcalI', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mathcalI')])
        self.mathcal_sym.append(['mathcalJ', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mathcalJ')])
        self.mathcal_sym.append(['mathcalK', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mathcalK')])
        self.mathcal_sym.append(['mathcalL', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mathcalL')])
        self.mathcal_sym.append(['mathcalM', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mathcalM')])
        self.mathcal_sym.append(['mathcalN', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mathcalN')])
        self.mathcal_sym.append(['mathcalO', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mathcalO')])
        self.mathcal_sym.append(['mathcalP', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mathcalP')])
        self.mathcal_sym.append(['mathcalQ', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mathcalQ')])
        self.mathcal_sym.append(['mathcalR', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mathcalR')])
        self.mathcal_sym.append(['mathcalS', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mathcalS')])
        self.mathcal_sym.append(['mathcalT', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mathcalT')])
        self.mathcal_sym.append(['mathcalU', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mathcalU')])
        self.mathcal_sym.append(['mathcalV', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mathcalV')])
        self.mathcal_sym.append(['mathcalW', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mathcalW')])
        self.mathcal_sym.append(['mathcalX', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mathcalX')])
        self.mathcal_sym.append(['mathcalY', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mathcalY')])
        self.mathcal_sym.append(['mathcalZ', 'win.insert-xml::' + CharacterDB.get_unicode_from_latex_name('mathcalZ')])
        self.symbols.append({'id': 'mathcal', 'name': 'Calligraphic Capitals', 'symbols': self.mathcal_sym})

        for section in self.symbols:
            self.add_headline(section['name'], section['id'])
            self.add_flowbox(section['symbols'], section['id'])

        self.set_child(self.box)

    def add_headline(self, name, css_class=None):
        header = Gtk.Label.new(name)
        header.set_xalign(Gtk.Align.FILL)
        header.add_css_class('header')
        if css_class:
            header.add_css_class(css_class)
        self.box.append(header)

    def add_flowbox(self, symbols, css_class=None):
        flowbox = Gtk.FlowBox()
        flowbox.set_selection_mode(Gtk.SelectionMode.NONE)
        flowbox.set_can_focus(False)
        flowbox.set_max_children_per_line(20)
        if css_class:
            flowbox.add_css_class(css_class)
        for data in symbols:
            image = Gtk.Image.new_from_icon_name('sidebar-' + data[0] + '-symbolic')
            image.set_valign(Gtk.Align.CENTER)
            image.set_halign(Gtk.Align.CENTER)
            button = Gtk.Button()
            button.set_child(image)
            button.set_detailed_action_name(data[1])
            button.set_can_focus(False)
            button.add_css_class('flat')
            flowbox.append(button)
        self.box.append(flowbox)

    def add_flowbox_for_pictures(self, symbols, css_class=None):
        flowbox = Gtk.FlowBox()
        flowbox.set_selection_mode(Gtk.SelectionMode.NONE)
        flowbox.set_can_focus(False)
        flowbox.set_max_children_per_line(20)
        if css_class:
            flowbox.add_css_class(css_class)
        for data in symbols:
            pic = Gtk.Picture.new_for_filename(os.path.join(self.resources_path, 'icons_extra', 'sidebar-' + data[0] + '-symbolic.svg'))
            pic.set_valign(Gtk.Align.CENTER)
            pic.set_halign(Gtk.Align.CENTER)
            button = Gtk.Button()
            button.set_child(pic)
            button.set_detailed_action_name(data[1])
            button.set_can_focus(False)
            button.add_css_class('flat')
            flowbox.append(button)
        self.box.append(flowbox)


