#!/usr/bin/env python3
# coding: utf-8

# Copyright (C) 2017-present Robert Griesel
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>


class AutocompleteDB(object):

    stylized_latex_to_xml = {
        'textendash': '–',
        'textemdash': '—',
        'guillemetleft': '«',
        'guillemetright': '»',
        'quotedblbase': '„',
        'textquotedblleft': '“',
        'textquotedblright': '”',
        'alpha': '𝛼',
        'beta': '𝛽',
        'gamma': '𝛾',
        'delta': '𝛿',
        'epsilon': '𝜖',
        'varepsilon': '𝜀',
        'zeta': '𝜁',
        'eta': '𝜂',
        'theta': '𝜃',
        'vartheta': '𝜗',
        'iota': '𝜄',
        'kappa': '𝜅',
        'lambda': '𝜆',
        'mu': '𝜇',
        'nu': '𝜈',
        'xi': '𝜉',
        'pi': '𝜋',
        'varpi': '𝜛',
        'rho': '𝜌',
        'varrho': '𝜚',
        'sigma': '𝜎',
        'varsigma': '𝜍',
        'tau': '𝜏',
        'upsilon': '𝜐',
        'phi': '𝜙',
        'varphi': '𝜑',
        'chi': '𝜒',
        'psi': '𝜓',
        'omega': '𝜔',
        'Gamma': 'Γ',
        'varGamma': '𝛤',
        'Delta': 'Δ',
        'varDelta': '𝛥',
        'Theta': 'Θ',
        'varTheta': '𝛩',
        'Lambda': 'Λ',
        'varLambda': '𝛬',
        'Xi': 'Ξ',
        'varXi': '𝛯',
        'Pi': 'Π',
        'varPi': '𝛱',
        'Sigma': 'Σ',
        'varSigma': '𝛴',
        'Upsilon': 'Υ',
        'varUpsilon': '𝛶',
        'Phi': 'Φ',
        'varPhi': '𝛷',
        'Psi': 'Ψ',
        'varPsi': '𝛹',
        'Omega': 'Ω',
        'varOmega': '𝛺',
        'leftarrow': '←',
        'leftrightarrow': '↔',
        'rightarrow': '→',
        'mapsto': '↦',
        'longleftarrow': '⟵',
        'longleftrightarrow': '⟷',
        'longrightarrow': '⟶',
        'longmapsto': '⟼',
        'downarrow': '↓',
        'updownarrow': '↕',
        'uparrow': '↑',
        'nwarrow': '↖',
        'searrow': '↘',
        'nearrow': '↗',
        'swarrow': '↙',
        'nleftarrow': '↚',
        'nleftrightarrow': '↮',
        'nrightarrow': '↛',
        'hookleftarrow': '↩',
        'hookrightarrow': '↪',
        'twoheadleftarrow': '↞',
        'twoheadrightarrow': '↠',
        'leftarrowtail': '↢',
        'rightarrowtail': '↣',
        'Leftarrow': '⇐',
        'Leftrightarrow': '⇔',
        'Rightarrow': '⇒',
        'Longleftarrow': '⟸',
        'Longleftrightarrow': '⟺',
        'Longrightarrow': '⟹',
        'Updownarrow': '⇕',
        'Uparrow': '⇑',
        'Downarrow': '⇓',
        'nLeftarrow': '⇍',
        'nLeftrightarrow': '⇎',
        'nRightarrow': '⇏',
        'leftleftarrows': '⇇',
        'leftrightarrows': '⇆',
        'rightleftarrows': '⇄',
        'rightrightarrows': '⇉',
        'downdownarrows': '⇊',
        'upuparrows': '⇈',
        'curvearrowleft': '↶',
        'curvearrowright': '↷',
        'Lsh': '↰',
        'Rsh': '↱',
        'looparrowleft': '↫',
        'looparrowright': '↬',
        'leftrightsquigarrow': '↭',
        'leftsquigarrow': '⇜',
        'rightsquigarrow': '⇝',
        'Lleftarrow': '⇚',
        'leftharpoondown': '↽',
        'rightharpoondown': '⇁',
        'leftharpoonup': '↼',
        'rightharpoonup': '⇀',
        'rightleftharpoons': '⇌',
        'leftrightharpoons': '⇋',
        'downharpoonleft': '⇃',
        'upharpoonleft': '↿',
        'downharpoonright': '⇂',
        'upharpoonright': '↾',
        'neg': '¬',
        'infty': '∞',
        'prime': '′',
        'backslash': '\\',
        'emptyset': '∅',
        'varnothing': '∅',
        'sharp': '♯',
        'flat': '♭',
        'natural': '♮',
        'angle': '∠',
        'sphericalangle': '∢',
        'measuredangle': '∡',
        'clubsuit': '♣',
        'diamondsuit': '♢',
        'heartsuit': '♡',
        'spadesuit': '♠',
        'forall': '∀',
        'exists': '∃',
        'nexists': '∄',
        'complement': '∁',
        'mathbbN': 'ℕ',
        'mathbbZ': 'ℤ',
        'mathbbQ': 'ℚ',
        'mathbbI': '𝕀',
        'mathbbR': 'ℝ',
        'mathbbC': 'ℂ',
        'Im': 'ℑ',
        'Re': 'ℜ',
        'aleph': 'ℵ',
        'wp': '℘',
        'hbar': 'ℏ',
        'imath': '𝚤',
        'jmath': '𝚥',
        'Bbbk': '𝕂',
        'ell': 'ℓ',
        'bot': '⊥',
        'top': '⊤',
        'partial': '∂',
        'nabla': '∇',
        'eth': 'ð',
        'mho': '℧',
        'pm': '±',
        'mp': '∓',
        'times': '×',
        'div': '÷',
        'ast': '∗',
        'star': '⋆',
        'circ': '◦',
        'bullet': '•',
        'divideontimes': '⋇',
        'ltimes': '⋉',
        'rtimes': '⋊',
        'cdot': '·',
        'dotplus': '∔',
        'leftthreetimes': '⋋',
        'rightthreetimes': '⋌',
        'amalg': '⨿',
        'otimes': '⊗',
        'oplus': '⊕',
        'ominus': '⊖',
        'oslash': '⊘',
        'odot': '⊙',
        'circledcirc': '⊚',
        'circleddash': '⊝',
        'circledast': '⊛',
        'bigtriangleup': '△',
        'bigtriangledown': '▽',
        'triangleleft': '◁',
        'triangleright': '▷',
        'cup': '∪',
        'cap': '∩',
        'uplus': '⊎',
        'wr': '≀',
        'setminus': '⧵',
        'sqcap': '⊓',
        'sqcup': '⊔',
        'wedge': '∧',
        'vee': '∨',
        'dagger': '†',
        'ddagger': '‡',
        'intercal': '⊺',
        'bowtie': '⋈',
        'propto': '∝',
        'multimap': '⊸',
        'pitchfork': '⋔',
        'therefore': '∴',
        'because': '∵',
        'neq': '≠',
        'equiv': '≡',
        'approx': '≈',
        'sim': '∼',
        'simeq': '≃',
        'cong': '≅',
        'ncong': '≇',
        'smile': '⌣',
        'frown': '⌢',
        'asymp': '≍',
        'between': '≬',
        'prec': '≺',
        'succ': '≻',
        'nprec': '⊀',
        'nsucc': '⊁',
        'preceq': '⪯',
        'succeq': '⪰',
        'perp': '⟂',
        'vdash': '⊢',
        'dashv': '⊣',
        'models': '⊧',
        'mid': '∣',
        'nmid': '∤',
        'parallel': '∥',
        'nparallel': '∦',
        'nless': '≮',
        'ngtr': '≯',
        'lessdot': '⋖',
        'gtrdot': '⋗',
        'll': '≪',
        'gg': '≫',
        'leq': '≤',
        'geq': '≥',
        'lneq': '⪇',
        'gneq': '⪈',
        'nleq': '≰',
        'ngeq': '≱',
        'vartriangleleft': '⊲',
        'vartriangleright': '⊳',
        'ntriangleleft': '⋪',
        'ntriangleright': '⋫',
        'trianglelefteq': '⊴',
        'trianglerighteq': '⊵',
        'ntrianglelefteq': '⋬',
        'ntrianglerighteq': '⋭',
        'subset': '⊂',
        'supset': '⊃',
        'nsubset': '⊄',
        'nsupset': '⊅',
        'subseteq': '⊆',
        'supseteq': '⊇',
        'subsetneq': '⊊',
        'supsetneq': '⊋',
        'nsubseteq': '⊈',
        'nsupseteq': '⊉',
        'sqsubset': '⊏',
        'sqsupset': '⊐',
        'sqsubseteq': '⊑',
        'sqsupseteq': '⊒',
        'in': '∈',
        'notin': '∉',
        'cdotp': '·',
        'colon': ':',
        'vdots': '⋮',
        'cdots': '⋯',
        'lparen': '(',
        'rparen': ')',
        'lbrack': '[',
        'rbrack': ']',
        'lbrace': '{',
        'rbrace': '}',
        'lfloor': '⌊',
        'rfloor': '⌋',
        'lceil': '⌈',
        'rceil': '⌉',
        'langle': '⟨',
        'rangle': '⟩',
        'vert': '|',
        'Vert': '‖',
        'mathcalA': '𝒜',
        'mathcalB': 'ℬ',
        'mathcalC': '𝒞',
        'mathcalD': '𝒟',
        'mathcalE': 'ℰ',
        'mathcalF': 'ℱ',
        'mathcalG': '𝒢',
        'mathcalH': 'ℋ',
        'mathcalI': 'ℐ',
        'mathcalJ': '𝒥',
        'mathcalK': '𝒦',
        'mathcalL': 'ℒ',
        'mathcalM': 'ℳ',
        'mathcalN': '𝒩',
        'mathcalO': '𝒪',
        'mathcalP': '𝒫',
        'mathcalQ': '𝒬',
        'mathcalR': 'ℛ',
        'mathcalS': '𝒮',
        'mathcalT': '𝒯',
        'mathcalU': '𝒰',
        'mathcalV': '𝒱',
        'mathcalW': '𝒲',
        'mathcalX': '𝒳',
        'mathcalY': '𝒴',
        'mathcalZ': '𝒵'
    }

    def get_suggestions(term):
        result = []
        for command in AutocompleteDB.stylized_latex_to_xml:
            if command.lower().startswith(term.lower()):
                result.append(command)
        return result

    def get_xml(command):
        if command in AutocompleteDB.stylized_latex_to_xml:
            return AutocompleteDB.stylized_latex_to_xml[command]


