#!/usr/bin/env python3
# coding: utf-8

# Copyright (C) 2017-present Robert Griesel
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>

from lemma.infrastructure.service_locator import ServiceLocator


class CharacterDB(object):

    alphabetical_symbols = {'𝑎', '𝑏', '𝑐', '𝑑', '𝑒', '𝑓', '𝑔', '\u210E', '𝑖', '𝑗', '𝑘', '𝑙', '𝑚', '𝑛', '𝑜', '𝑝', '𝑞', '𝑟', '𝑠', '𝑡', '𝑢', '𝑣', '𝑤', '𝑥', '𝑦', '𝑧', '𝐴', '𝐵', '𝐶', '𝐷', '𝐸', '𝐹', '𝐺', '𝐻', '𝐼', '𝐽', '𝐾', '𝐿', '𝑀', '𝑁', '𝑂', '𝑃', '𝑄', '𝑅', '𝑆', '𝑇', '𝑈', '𝑉', '𝑊', '𝑋', '𝑌', '𝑍', '𝛼', '𝛽', '𝛾', '𝛿', '𝜀', '𝜁', '𝜂', '𝜃', '𝜄', '𝜅', '𝜆', '𝜇', '𝜈', '𝜉', '𝜊', '𝜋', '𝜌', '𝜍', '𝜎', '𝜏', '𝜐', '𝜑', '𝜒', '𝜓', '𝜔', '𝜕', '𝜖', '𝜗', '𝜘', '𝜙', '𝜚', '𝜛', '𝛢', '𝛣', '𝛤', '𝛥', '𝛦', '𝛧', '𝛨', '𝛩', '𝛪', '𝛫', '𝛬', '𝛭', '𝛮', '𝛯', '𝛰', '𝛱', '𝛲', '𝛳', '𝛴', '𝛵', '𝛶', '𝛷', '𝛸', '𝛹', '𝛺', 'α', 'β', 'γ', 'δ', 'ε', 'ζ', 'η', 'θ', 'ι', 'κ', 'λ', 'μ', 'ν', 'ξ', 'ο', 'π', 'ρ', 'ς', 'σ', 'τ', 'υ', 'φ', 'χ', 'ψ', 'ω', 'ϊ', 'ϋ', 'ό', 'ύ', 'ώ', 'Ϗ', 'ϐ', 'ϑ', 'ϒ', 'ϓ', 'ϔ', 'ϕ', 'ϖ', 'ϗ', 'Ϙ', 'ϙ', 'Ϛ', 'ϛ', 'Ϝ', 'ϝ', 'Ϟ', 'ϟ', 'Ϡ', 'ϡ', 'Ϣ', 'ϣ', 'Ϥ', 'ϥ', 'Ϧ', 'ϧ', 'Ϩ', 'ϩ', 'Ϫ', 'ϫ', 'Ϭ', 'ϭ', 'Ϯ', 'ϯ', 'ϰ', 'ϱ', 'ϲ', 'ϳ', 'ϴ', 'ϵ', 'Α', 'Β', 'Γ', 'Δ', 'Ε', 'Ζ', 'Η', 'Θ', 'Ι', 'Κ', 'Λ', 'Μ', 'Ν', 'Ξ', 'Ο', 'Π', 'Ρ', 'Σ', 'Τ', 'Υ', 'Φ', 'Χ', 'Ψ', 'Ω', '𝒜', 'ℬ', '𝒞', '𝒟', 'ℰ', 'ℱ', '𝒢', 'ℋ', 'ℐ', '𝒥', '𝒦', 'ℒ', 'ℳ', '𝒩', '𝒪', '𝒫', '𝒬', 'ℛ', '𝒮', '𝒯', '𝒰', '𝒱', '𝒲', '𝒳', '𝒴', '𝒵'}
    ordinary_symbols = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '!', '?', '.', '|', '‖', '/', '′', '@', '"', '¬', '∞', '\\', '∅', '♯', '♭', '♮', '∠', '∢', '∡', '♣', '♢', '♡', '♠', '∀', '∃', '∄', '∁', 'ℕ', 'ℤ', 'ℚ', '𝕀', 'ℝ', 'ℂ', 'ℑ', 'ℜ', 'ℵ', '℘', 'ℏ', '𝚤', '𝚥', '𝕂', 'ℓ', '⊥', '⊤', '∂', '∇', 'ð', '℧', '⋮', '⋯'}
    binary_operations = {'+', '−', '∗', '±', '∓', '×', '÷', '∗', '⋆', '◦', '•', '⋇', '⋉', '⋊', '·', '∔', '⋋', '⋌', '⨿', '⊗', '⊕', '⊖', '⊘', '⊙', '⊚', '⊝', '⊛', '△', '▽', '◁', '▷', '∪', '∩', '⊎', '≀', '⧵', '⊓', '⊔', '∧', '∨', '†', '‡', '⊺'}
    relations = {'=', '<', '>', ':', '⁐', '←', '↑', '→', '↓', '↔', '↕', '↖', '↗', '↘', '↙', '↚', '↛', '↜', '↝', '↞', '↟', '↠', '↡', '↢', '↣', '↤', '↥', '↦', '↧', '↨', '↩', '↪', '↫', '↬', '↭', '↮', '↯', '↰', '↱', '↲', '↳', '↶', '↷', '↼', '↽', '↾', '↿', '⇀', '⇁', '⇂', '⇃', '⇄', '⇅', '⇆', '⇇', '⇈', '⇉', '⇊', '⇋', '⇌', '⇍', '⇎', '⇏', '⇐', '⇑', '⇒', '⇓', '⇔', '⇕', '⇖', '⇗', '⇘', '⇙', '⇚', '⇛', '⇜', '⇝', '⇤', '⇥', '⇴', '⇵', '⇶', '⇷', '⇸', '⇹', '⇺', '⇻', '⇼', '⇽', '⇾', '⇿', '⟵', '⟶', '⟷', '⟸', '⟹', '⟺', '⟻', '⟼', '∈', '∉', '⋈', '∝', '⊸', '⋔', '∴', '∵', '≠', '≡', '≈', '∼', '≃', '≅', '≇', '⌣', '⌢', '≍', '≬', '≺', '≻', '⊀', '⊁', '⪯', '⪰', '⟂', '⊢', '⊣', '⊧', '∣', '∤', '∥', '∦', '≮', '≯', '⋖', '⋗', '≪', '≫', '≤', '≥', '⪇', '⪈', '≰', '≱', '⊲', '⊳', '⋪', '⋫', '⊴', '⊵', '⋬', '⋭', '⊂', '⊃', '⊄', '⊅', '⊆', '⊇', '⊊', '⊋', '⊈', '⊉', '⊏', '⊐', '⊑', '⊒', '∈', '∉'}
    punctuation_marks = {',', ';'}
    opening_symbols = {'(', '[', '{', '⌊', '⌈', '⟨'}
    closing_symbols = {')', ']', '}', '⌋', '⌉', '⟩'}
    latex_to_unicode = {
        'textendash': '–',
        'textemdash': '—',
        'guillemetleft': '«',
        'guillemetright': '»',
        'quotedblbase': '„',
        'textquotedblleft': '“',
        'textquotedblright': '”',
        'alpha': '𝛼',
        'beta': '𝛽',
        'gamma': '𝛾',
        'delta': '𝛿',
        'epsilon': '𝜖',
        'varepsilon': '𝜀',
        'zeta': '𝜁',
        'eta': '𝜂',
        'theta': '𝜃',
        'vartheta': '𝜗',
        'iota': '𝜄',
        'kappa': '𝜅',
        'lambda': '𝜆',
        'mu': '𝜇',
        'nu': '𝜈',
        'xi': '𝜉',
        'pi': '𝜋',
        'varpi': '𝜛',
        'rho': '𝜌',
        'varrho': '𝜚',
        'sigma': '𝜎',
        'varsigma': '𝜍',
        'tau': '𝜏',
        'upsilon': '𝜐',
        'phi': '𝜙',
        'varphi': '𝜑',
        'chi': '𝜒',
        'psi': '𝜓',
        'omega': '𝜔',
        'Gamma': 'Γ',
        'varGamma': '𝛤',
        'Delta': 'Δ',
        'varDelta': '𝛥',
        'Theta': 'Θ',
        'varTheta': '𝛩',
        'Lambda': 'Λ',
        'varLambda': '𝛬',
        'Xi': 'Ξ',
        'varXi': '𝛯',
        'Pi': 'Π',
        'varPi': '𝛱',
        'Sigma': 'Σ',
        'varSigma': '𝛴',
        'Upsilon': 'Υ',
        'varUpsilon': '𝛶',
        'Phi': 'Φ',
        'varPhi': '𝛷',
        'Psi': 'Ψ',
        'varPsi': '𝛹',
        'Omega': 'Ω',
        'varOmega': '𝛺',
        'leftarrow': '←',
        'leftrightarrow': '↔',
        'rightarrow': '→',
        'mapsto': '↦',
        'longleftarrow': '⟵',
        'longleftrightarrow': '⟷',
        'longrightarrow': '⟶',
        'longmapsto': '⟼',
        'downarrow': '↓',
        'updownarrow': '↕',
        'uparrow': '↑',
        'nwarrow': '↖',
        'searrow': '↘',
        'nearrow': '↗',
        'swarrow': '↙',
        'nleftarrow': '↚',
        'nleftrightarrow': '↮',
        'nrightarrow': '↛',
        'hookleftarrow': '↩',
        'hookrightarrow': '↪',
        'twoheadleftarrow': '↞',
        'twoheadrightarrow': '↠',
        'leftarrowtail': '↢',
        'rightarrowtail': '↣',
        'Leftarrow': '⇐',
        'Leftrightarrow': '⇔',
        'Rightarrow': '⇒',
        'Longleftarrow': '⟸',
        'Longleftrightarrow': '⟺',
        'Longrightarrow': '⟹',
        'Updownarrow': '⇕',
        'Uparrow': '⇑',
        'Downarrow': '⇓',
        'nLeftarrow': '⇍',
        'nLeftrightarrow': '⇎',
        'nRightarrow': '⇏',
        'leftleftarrows': '⇇',
        'leftrightarrows': '⇆',
        'rightleftarrows': '⇄',
        'rightrightarrows': '⇉',
        'downdownarrows': '⇊',
        'upuparrows': '⇈',
        'curvearrowleft': '↶',
        'curvearrowright': '↷',
        'Lsh': '↰',
        'Rsh': '↱',
        'looparrowleft': '↫',
        'looparrowright': '↬',
        'leftrightsquigarrow': '↭',
        'leftsquigarrow': '⇜',
        'rightsquigarrow': '⇝',
        'Lleftarrow': '⇚',
        'leftharpoondown': '↽',
        'rightharpoondown': '⇁',
        'leftharpoonup': '↼',
        'rightharpoonup': '⇀',
        'rightleftharpoons': '⇌',
        'leftrightharpoons': '⇋',
        'downharpoonleft': '⇃',
        'upharpoonleft': '↿',
        'downharpoonright': '⇂',
        'upharpoonright': '↾',
        'neg': '¬',
        'infty': '∞',
        'prime': '′',
        'backslash': '\\',
        'emptyset': '∅',
        'varnothing': '∅',
        'sharp': '♯',
        'flat': '♭',
        'natural': '♮',
        'angle': '∠',
        'sphericalangle': '∢',
        'measuredangle': '∡',
        'clubsuit': '♣',
        'diamondsuit': '♢',
        'heartsuit': '♡',
        'spadesuit': '♠',
        'forall': '∀',
        'exists': '∃',
        'nexists': '∄',
        'complement': '∁',
        'mathbbN': 'ℕ',
        'mathbbZ': 'ℤ',
        'mathbbQ': 'ℚ',
        'mathbbI': '𝕀',
        'mathbbR': 'ℝ',
        'mathbbC': 'ℂ',
        'Im': 'ℑ',
        'Re': 'ℜ',
        'aleph': 'ℵ',
        'wp': '℘',
        'hbar': 'ℏ',
        'imath': '𝚤',
        'jmath': '𝚥',
        'Bbbk': '𝕂',
        'ell': 'ℓ',
        'bot': '⊥',
        'top': '⊤',
        'partial': '∂',
        'nabla': '∇',
        'eth': 'ð',
        'mho': '℧',
        'pm': '±',
        'mp': '∓',
        'times': '×',
        'div': '÷',
        'ast': '∗',
        'star': '⋆',
        'circ': '◦',
        'bullet': '•',
        'divideontimes': '⋇',
        'ltimes': '⋉',
        'rtimes': '⋊',
        'cdot': '·',
        'dotplus': '∔',
        'leftthreetimes': '⋋',
        'rightthreetimes': '⋌',
        'amalg': '⨿',
        'otimes': '⊗',
        'oplus': '⊕',
        'ominus': '⊖',
        'oslash': '⊘',
        'odot': '⊙',
        'circledcirc': '⊚',
        'circleddash': '⊝',
        'circledast': '⊛',
        'bigtriangleup': '△',
        'bigtriangledown': '▽',
        'triangleleft': '◁',
        'triangleright': '▷',
        'cup': '∪',
        'cap': '∩',
        'uplus': '⊎',
        'wr': '≀',
        'setminus': '⧵',
        'sqcap': '⊓',
        'sqcup': '⊔',
        'wedge': '∧',
        'vee': '∨',
        'dagger': '†',
        'ddagger': '‡',
        'intercal': '⊺',
        'bowtie': '⋈',
        'propto': '∝',
        'multimap': '⊸',
        'pitchfork': '⋔',
        'therefore': '∴',
        'because': '∵',
        'neq': '≠',
        'equiv': '≡',
        'approx': '≈',
        'sim': '∼',
        'simeq': '≃',
        'cong': '≅',
        'ncong': '≇',
        'smile': '⌣',
        'frown': '⌢',
        'asymp': '≍',
        'between': '≬',
        'prec': '≺',
        'succ': '≻',
        'nprec': '⊀',
        'nsucc': '⊁',
        'preceq': '⪯',
        'succeq': '⪰',
        'perp': '⟂',
        'vdash': '⊢',
        'dashv': '⊣',
        'models': '⊧',
        'mid': '∣',
        'nmid': '∤',
        'parallel': '∥',
        'nparallel': '∦',
        'nless': '≮',
        'ngtr': '≯',
        'lessdot': '⋖',
        'gtrdot': '⋗',
        'll': '≪',
        'gg': '≫',
        'leq': '≤',
        'geq': '≥',
        'lneq': '⪇',
        'gneq': '⪈',
        'nleq': '≰',
        'ngeq': '≱',
        'vartriangleleft': '⊲',
        'vartriangleright': '⊳',
        'ntriangleleft': '⋪',
        'ntriangleright': '⋫',
        'trianglelefteq': '⊴',
        'trianglerighteq': '⊵',
        'ntrianglelefteq': '⋬',
        'ntrianglerighteq': '⋭',
        'subset': '⊂',
        'supset': '⊃',
        'nsubset': '⊄',
        'nsupset': '⊅',
        'subseteq': '⊆',
        'supseteq': '⊇',
        'subsetneq': '⊊',
        'supsetneq': '⊋',
        'nsubseteq': '⊈',
        'nsupseteq': '⊉',
        'sqsubset': '⊏',
        'sqsupset': '⊐',
        'sqsubseteq': '⊑',
        'sqsupseteq': '⊒',
        'in': '∈',
        'notin': '∉',
        'cdotp': '·',
        'colon': ':',
        'vdots': '⋮',
        'cdots': '⋯',
        'lparen': '(',
        'rparen': ')',
        'lbrack': '[',
        'rbrack': ']',
        'lbrace': '{',
        'rbrace': '}',
        'lfloor': '⌊',
        'rfloor': '⌋',
        'lceil': '⌈',
        'rceil': '⌉',
        'langle': '⟨',
        'rangle': '⟩',
        'vert': '|',
        'Vert': '‖',
        'mathcalA': '𝒜',
        'mathcalB': 'ℬ',
        'mathcalC': '𝒞',
        'mathcalD': '𝒟',
        'mathcalE': 'ℰ',
        'mathcalF': 'ℱ',
        'mathcalG': '𝒢',
        'mathcalH': 'ℋ',
        'mathcalI': 'ℐ',
        'mathcalJ': '𝒥',
        'mathcalK': '𝒦',
        'mathcalL': 'ℒ',
        'mathcalM': 'ℳ',
        'mathcalN': '𝒩',
        'mathcalO': '𝒪',
        'mathcalP': '𝒫',
        'mathcalQ': '𝒬',
        'mathcalR': 'ℛ',
        'mathcalS': '𝒮',
        'mathcalT': '𝒯',
        'mathcalU': '𝒰',
        'mathcalV': '𝒱',
        'mathcalW': '𝒲',
        'mathcalX': '𝒳',
        'mathcalY': '𝒴',
        'mathcalZ': '𝒵'
    }
    replacements = {
        '--': '–',
        '---': '—',
        '<<': '«',
        '>>': '»',
        ',,': '„',
        '``': '“',
        '´´': '”',
        '\'\'': '”'
    }

    def get_unicode_from_latex_name(name):
        return CharacterDB.latex_to_unicode[name]

    def is_mathsymbol(char):
        return char in CharacterDB.ordinary_symbols or char in CharacterDB.binary_operations or char in CharacterDB.relations or char in CharacterDB.punctuation_marks or char in CharacterDB.opening_symbols or char in CharacterDB.closing_symbols or char in CharacterDB.alphabetical_symbols

    def is_ordinary_symbol(char):
        return char in CharacterDB.ordinary_symbols or char in CharacterDB.alphabetical_symbols

    def is_binary_operation(char):
        return char in CharacterDB.binary_operations

    def is_relation(char):
        return char in CharacterDB.relations

    def is_punctuation_mark(char):
        return char in CharacterDB.punctuation_marks

    def is_opening_symbol(char):
        return char in CharacterDB.opening_symbols

    def is_closing_symbol(char):
        return char in CharacterDB.closing_symbols

    def is_whitespace(char):
        return (ServiceLocator.get_regex_matcher('\\s').match(char) != None)

    def has_replacement(text):
        return text in CharacterDB.replacements

    def get_replacement(text):
        return CharacterDB.replacements[text]


